version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    environment:
        - VITE_API_URL=http://backend:8080  # Frontend nutzt den Backend-Container


  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/Flohmarkt


  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network: